---
title: "コントローラー中でsend_dataの後にredirect_toを呼ぶとエラーが出る理由"
emoji: "🦧"
type: "tech" # tech: 技術記事 / idea: アイデア
topics: ['Rails', 'Ruby']
published: false
---

## send_dataでファイルを出力した後にリダイレクトしようとするとエラーが出る

(send_data)[https://railsdoc.com/page/send_data]した後にリダイレクトする処理を書いたアクションを用意しルーティングを設定します。

```ruby
class SampleController < ApplicationController
  def hoge
    send_data('hoge', filename: 'hoge.txt')
    render html: "<h2>hello world</h2>".html_safe
  end
end
```

その上でページに遷移するとエラーが出ます。
これはsend_dataメソッドがレスポンスを返すロジックであるため二重にレスポンスす返す処理を書いてしまっているためです。

```txt
Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...) and return".
```

ここでエラーメッセージを見てみると`Please note that you may only call render OR redirect, and at most once per action.`とあります。しかしアクション内で`redirect_to`メソッドは一度しか使用しておらず`render`メソッドに至っては呼ばれていません。調査してみましょう。


## 調査
### 仮説
「`send_data`が内部的に`render`メソッドを呼び出している」などがありえそうです。

### binding.irbで調査
`bindng.irb`を挟んで調査します。

```ruby
class SampleController < ApplicationController
  def hello
    binding.irb
    send_data('hoge', filename: 'hoge.txt')
    render html: "<h2>hello world</h2>".html_safe
  end
end
```

`method(:send_data).source_location`でメソッドが定義されている場所を特定すると次のコードが見つかりました。

https://github.com/rails/rails/blob/f8e97a1464e0ab7feabf87f9da7fd9a86af509a0/actionpack/lib/action_controller/metal/instrumentation.rb#L34-L38

